package com.playtranslate.ui

/**
 * Builds [CardOutputs] from the sheet-side state. The send-time
 * dispatcher passes the resulting struct to
 * [AnkiCardTypeMapper.assembleNote] alongside the user's saved field
 * mapping; each [ContentSource] picks one string from the outputs.
 *
 * Word-card definition HTML is supplied by the caller (the word sheet)
 * because it depends on per-card curation state (`removedSenses`,
 * `removedExamples`, `removedTatoebaIdx`). Sentence-card definition is
 * derived inline from the first highlighted word's `meaning`.
 */
object AnkiCardOutputBuilder {

    /**
     * Wraps an AnkiDroid-side media filename in the `<img>` markup
     * mining templates expect in their Picture/Screenshot field.
     *
     * Why wrap here and not pass the bare filename: Lapis, JPMN,
     * Migaku, and Anki Basic all render their picture-slot field via a
     * literal `{{Picture}}` (or `{{Screenshot}}`) mustache — they don't
     * wrap the field's contents in `<img>` themselves. The Yomitan
     * ecosystem convention is for the field to ALREADY contain `<img>`
     * markup, typically generated by Yomitan's `{screenshot-html}`
     * marker. The legacy v004 path wraps internally (see
     * SentenceAnkiHtmlBuilder.buildBackHtml), so this is the structured
     * path's parallel.
     *
     * `max-width:100%` keeps the image from busting out of narrow card
     * widths on mobile AnkiDroid. We deliberately don't ship
     * border-radius / margins — those are template-styling concerns
     * the user's CSS should own.
     */
    private fun pictureHtml(imageFilename: String?): String =
        if (imageFilename.isNullOrEmpty()) ""
        else "<img src=\"$imageFilename\" style=\"max-width:100%;\">"

    /**
     * Builds outputs from a sentence sheet's current state. The caller
     * may supply pre-rendered [examplesHtml] (Tatoeba pairs for the
     * highlighted word) — usually available only when the send is
     * routed through [WordAnkiReviewSheet], which carries the
     * surrounding word-lookup context. Sentence-only flows
     * ([AnkiReviewBottomSheet]) pass empty.
     */
    fun forSentence(
        cardData: SentenceAnkiContentFragment.CardData,
        imageFilename: String?,
        examplesHtml: String = "",
    ): CardOutputs {
        val firstHighlighted = cardData.words.firstOrNull {
            it.word in cardData.selectedWords
        }
        // EXPRESSION: highlighted word's plain headword text (no
        // brackets). For template fields that render `{{Expression}}`
        // raw — like Lapis's vocab-card front — putting brackets here
        // shows literal `[reading]` markup. Templates that want
        // furigana on the Expression use EXPRESSION_FURIGANA below.
        // Falls back to the whole sentence when nothing is highlighted
        // so the field is non-empty (matters when a model uses
        // sortf=0 and EXPRESSION lands at the sort slot).
        val expression = firstHighlighted?.word
            ?: cardData.source.replace(Regex("[\\n\\r]+"), " ").trim()
        // EXPRESSION_FURIGANA: per-kanji bracketed headword for fields
        // wrapped with `{{furigana:}}` (Lapis ExpressionFurigana,
        // Migaku Target Word, etc.). Empty when nothing is highlighted.
        val expressionFurigana = firstHighlighted?.let {
            SentenceAnkiHtmlBuilder.buildExpressionFurigana(
                word = it.word, reading = it.reading,
                sourceLangId = cardData.sourceLangId,
            )
        }.orEmpty()
        val reading = firstHighlighted?.reading.orEmpty()
        // DEFINITION: empty when nothing's highlighted. assembleNote's
        // sentence-mode fold (not yet implemented for this flow; see
        // plan §3 — left explicit "" so the WORDS_TABLE is what a user
        // would map their main definition field to instead).
        val definition = firstHighlighted?.meaning?.let { m ->
            m.lines().filter { it.isNotBlank() }
                .joinToString("<br>") { it.trimStart() }
        }.orEmpty()
        val frequency = firstHighlighted?.let {
            SentenceAnkiHtmlBuilder.starsString(it.freqScore)
        }.orEmpty()
        // SENTENCE: plain sentence text with `<b>` around highlighted
        // surface forms. For fields rendered raw via `{{Sentence}}` —
        // JPMN's Sentence on every card type, Lapis's Sentence when no
        // filter wraps it — putting bracket syntax here shows literal
        // markup. The bracketed variant goes in SENTENCE_FURIGANA below.
        val sentenceHtml = SentenceAnkiHtmlBuilder.buildSentencePlain(
            text = cardData.source,
            words = cardData.words,
            highlightedWords = cardData.selectedWords,
        )
        // SENTENCE_FURIGANA: bracketed + `<wbr>` variant with `<b>`
        // around the highlighted bracketed block (matches JPMN's
        // `<b> 偽者[にせもの]</b>` shape). For fields wrapped with
        // `{{furigana:}}` (Lapis SentenceFurigana, JPMN SentenceReading,
        // Migaku Sentence).
        val sentenceFuriganaHtml = SentenceAnkiHtmlBuilder.buildSentenceFurigana(
            text = cardData.source,
            words = cardData.words,
            highlightedWords = cardData.selectedWords,
            sourceLangId = cardData.sourceLangId,
        )
        val translationHtml = cardData.target.replace(Regex("[\\n\\r]+"), "<br>")
        val sortedWords = if (cardData.selectedWords.isNotEmpty()) {
            cardData.words.sortedByDescending { it.word in cardData.selectedWords }
        } else cardData.words
        val wordsHtml = SentenceAnkiHtmlBuilder.buildWordsHtmlWith(
            sortedWords,
            cardData.selectedWords,
            styler = inlineStyler,
        )
        return CardOutputs(
            expression = expression,
            expressionFurigana = expressionFurigana,
            reading = reading,
            sentence = sentenceHtml,
            sentenceFurigana = sentenceFuriganaHtml,
            sentenceTranslation = translationHtml,
            picture = pictureHtml(imageFilename),
            definition = definition,
            examples = examplesHtml,
            frequency = frequency,
            partOfSpeech = "",
            wordsTable = wordsHtml,
            // Flag values for sentence-mode sends:
            //  - SENTENCE_CARD_FLAG always fires (Lapis/JPMN signal).
            //  - TARGETED_SENTENCE_CARD_FLAG fires only when there's a
            //    bolded word to target (JPMN's IsTargetedSentenceCard
            //    requires a bolded word in the Sentence field, which
            //    wrapHighlighted only produces with selectedWords).
            //  - VOCABULARY_CARD_FLAG stays empty — sentence sends are
            //    not vocab-variant cards.
            //  - ALWAYS_ON_MARKER fires for users who manually mapped a
            //    flag field to always-on.
            vocabularyCardFlag = "",
            sentenceCardFlag = "x",
            targetedSentenceCardFlag = if (cardData.selectedWords.isNotEmpty()) "x" else "",
            alwaysOnMarker = "x",
        )
    }

    /**
     * Builds outputs from a word-sheet send. [definitionHtml] is the
     * caller's pre-rendered Definition HTML (built via
     * `WordAnkiReviewSheet.buildWordDefinitionHtml(inlineStyler)`)
     * because it depends on the sheet's curation state. Same for
     * [examplesHtml] (Tatoeba pairs, honoring `removedTatoebaIdx`).
     */
    fun forWord(
        word: String,
        reading: String,
        pos: String,
        definitionHtml: String,
        freqScore: Int,
        imageFilename: String?,
        examplesHtml: String = "",
        sourceLangId: com.playtranslate.language.SourceLangId =
            com.playtranslate.language.SourceLangId.JA,
    ): CardOutputs = CardOutputs(
        // EXPRESSION: plain headword text — for fields rendered raw
        // via `{{Expression}}` (Lapis vocab-card front, Hint, etc.).
        expression = word,
        // EXPRESSION_FURIGANA: per-kanji bracketed headword for fields
        // wrapped with `{{furigana:}}` (Lapis ExpressionFurigana,
        // Migaku Target Word, etc.).
        expressionFurigana = SentenceAnkiHtmlBuilder.buildExpressionFurigana(
            word = word, reading = reading, sourceLangId = sourceLangId,
        ),
        reading = reading,
        sentence = "",
        sentenceFurigana = "",
        sentenceTranslation = "",
        picture = pictureHtml(imageFilename),
        definition = definitionHtml,
        examples = examplesHtml,
        frequency = SentenceAnkiHtmlBuilder.starsString(freqScore),
        partOfSpeech = pos,
        wordsTable = "",
        // Flag values for word-mode sends: VOCABULARY_CARD_FLAG fires
        // (Migaku/Lapis vocab-variant signal); sentence flags stay
        // empty since word cards aren't sentence-variant. ALWAYS_ON
        // fires for manually-mapped always-on flag fields.
        vocabularyCardFlag = "x",
        sentenceCardFlag = "",
        targetedSentenceCardFlag = "",
        alwaysOnMarker = "x",
    )

}
